# Higress社区治理Agent配置文件

# Agent基础配置
agent:
  name: "higress-community-agent"
  version: "1.0.0"
  port: 8080
  debug: true

# OpenAI配置
openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4o"
  max_tokens: 4000
  temperature: 0.7

# DeepWiki MCP配置
deepwiki:
  enabled: true
  endpoint: "https://mcp.deepwiki.com/mcp"
  timeout: "30s"
  max_retries: 3

# Higress文档配置
higress:
  docs_url: "https://higress.io/docs"
  cache_duration: "1h"
  max_concurrent_requests: 10

# 知识库配置
knowledge:
  enabled: true
  storage_path: "./data/knowledge"
  max_size: "1GB"
  update_interval: "24h"

# 知识融合配置
fusion:
  enabled: true
  similarity_threshold: 0.7
  max_sources: 5
  response_format: "markdown"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "./logs/agent.log"

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: "30s" 