# Higress社区治理Agent配置文件

# Agent基础配置
agent:
  name: "higress-community-agent"
  version: "1.0.0"
  port: 8080
  debug: true

# OpenAI配置
openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4o"
  max_tokens: 4000
  temperature: 0.7

# DeepWiki MCP配置
deepwiki:
  enabled: true
  endpoint: "https://mcp.deepwiki.com/mcp"
  api_key: "${DEEPWIKI_API_KEY}"
  timeout: "30s"
  max_retries: 3

# Higress配置
higress:
  docs_url: "https://higress.io/docs"
  repo_owner: "alibaba"
  repo_name: "higress"
  cache_duration: "1h"
  max_concurrent_requests: 10

# GitHub配置
github:
  token: "${GITHUB_TOKEN}"
  api_url: "https://api.github.com"
  timeout: "30s"
  max_retries: 3

# 知识库配置
knowledge:
  enabled: true
  storage_path: "./data/knowledge"
  max_size: "1GB"
  update_interval: "24h"

# 知识融合配置
fusion:
  enabled: true
  similarity_threshold: 0.7
  max_sources: 5
  response_format: "markdown"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "./logs/agent.log"

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: "30s"

# 工具配置
tools:
  bug_analyzer:
    enabled: true
    max_stack_trace_length: 10000
    supported_languages: ["go", "java", "python", "javascript"]
  
  image_analyzer:
    enabled: true
    max_image_size: "10MB"
    supported_formats: ["png", "jpg", "jpeg", "gif"]
  
  issue_classifier:
    enabled: true
    categories: ["bug", "feature", "enhancement", "documentation", "question"]
    priorities: ["low", "normal", "high", "urgent", "critical"]
  
  github_manager:
    enabled: true
    auto_label: true
    auto_assign: true
  
  community_stats:
    enabled: true
    update_interval: "1h"
    cache_duration: "24h"

# 安全配置
security:
  cors_enabled: true
  allowed_origins: ["*"]
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: "1m"

# 缓存配置
cache:
  enabled: true
  redis_url: "${REDIS_URL}"
  default_ttl: "1h"
  max_size: 1000

# 记忆组件配置
memory:
  working_memory_max_items: 20
  working_memory_ttl: "30m"
  short_term_memory_slots: 16
  short_term_memory_ttl: "2h"
  cleanup_interval: "5m"
  importance_threshold: 0.3

# 网络配置
network:
  proxy_enabled: false  # 是否启用代理
  proxy_url: ""        # 代理URL (例如: http://proxy.example.com:8080)
  proxy_type: "http"   # 代理类型 (http, https, socks5)

# MCP集成配置
mcp:
  enabled: true
  timeout: "30s"
  servers:
    deepwiki:
      enabled: true
      server_url: "https://mcp.deepwiki.com/mcp"
      server_label: "deepwiki"
      require_approval: "never"
      allowed_tools: ["ask_question", "read_wiki_structure"]
    
    stripe:
      enabled: false
      server_url: "https://mcp.stripe.com"
      server_label: "stripe"
      require_approval: "always"
      headers:
        Authorization: "${STRIPE_API_KEY}"
    
    shopify:
      enabled: false
      server_url: "https://mcp.shopify.com"
      server_label: "shopify"
      require_approval: "always"
      headers:
        Authorization: "${SHOPIFY_API_KEY}" 